// Confirmed-working governor RSS feeds as of May 2026.
// Each entry: { state, feed, name }
export const STATE_FEEDS = [
  { state: 'AL', feed: 'https://governor.alabama.gov/feed/',                                                                          name: 'Alabama' },
  { state: 'AK', feed: 'https://gov.alaska.gov/newsroom/feed/',                                                                       name: 'Alaska' },
  { state: 'AR', feed: 'https://governor.arkansas.gov/feed/',                                                                         name: 'Arkansas' },
  { state: 'AZ', feed: 'https://azgovernor.gov/newsroom/feed/',                                                                       name: 'Arizona' },
  { state: 'CA', feed: 'https://www.gov.ca.gov/feed/',                                                                                name: 'California' },
  { state: 'DE', feed: 'https://governor.delaware.gov/feed/',                                                                         name: 'Delaware' },
  { state: 'GA', feed: 'https://gov.georgia.gov/rss.xml',                                                                             name: 'Georgia' },
  { state: 'HI', feed: 'https://governor.hawaii.gov/feed/',                                                                           name: 'Hawaii' },
  { state: 'ID', feed: 'https://gov.idaho.gov/feed/',                                                                                 name: 'Idaho' },
  { state: 'IL', feed: 'https://gov-pritzker-newsroom.prezly.com/feed',                                                               name: 'Illinois' },
  { state: 'IA', feed: 'https://governor.iowa.gov/news/all/all/all/rss.xml',                                                          name: 'Iowa' },
  { state: 'LA', feed: 'https://gov.louisiana.gov/news/rss',                                                                          name: 'Louisiana' },
  { state: 'ME', feed: 'https://www.maine.gov/governor/mills/rss.xml',                                                                name: 'Maine' },
  { state: 'MN', feed: 'https://mn.gov/governor/rest/rss/Newsroom?id=1055-35332&detailPage=/governor/newsroom/press-releases/index.jsp', name: 'Minnesota' },
  { state: 'MO', feed: 'https://governor.mo.gov/rss.xml',                                                                             name: 'Missouri' },
  { state: 'MS', feed: 'https://governorreeves.ms.gov/feed/',                                                                         name: 'Mississippi' },
  { state: 'NC', feed: 'https://governor.nc.gov/news/feed',                                                                           name: 'North Carolina' },
  { state: 'NE', feed: 'https://governor.nebraska.gov/rss.xml',                                                                       name: 'Nebraska' },
  { state: 'NM', feed: 'https://www.governor.state.nm.us/feed/',                                                                      name: 'New Mexico' },
  { state: 'ND', feed: 'https://www.governor.nd.gov/rss/news',                                                                        name: 'North Dakota' },
  { state: 'RI', feed: 'https://governor.ri.gov/press-releases.xml',                                                                  name: 'Rhode Island' },
  { state: 'TX', feed: 'https://gov.texas.gov/news/rss',                                                                              name: 'Texas' },
  { state: 'UT', feed: 'https://governor.utah.gov/feed/',                                                                             name: 'Utah' },
  { state: 'WA', feed: 'https://www.governor.wa.gov/rss/news.xml',                                                                    name: 'Washington' },
  { state: 'WV', feed: 'https://governor.wv.gov/rss.xml',                                                                             name: 'West Virginia' },
];
